# $OpenBSD$

COMMENT =	a tool to fingerprint web site components

DISTNAME =	whatweb-0.4.7
CATEGORIES =	security

MAINTAINER =	Jonathan Armani <armani@openbsd.org>

HOMEPAGE = http://www.morningstarsecurity.com/research/whatweb
MASTER_SITES =	http://www.morningstarsecurity.com/downloads/

# GPLv2
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

MODULES =	lang/ruby

RUN_DEPENDS =	${MODRUBY_ICONV_DEPENDS}

.include <bsd.port.mk>
