# $OpenBSD$

COMMENT =	an object for all network related stuff	

MODULES =	cpan
DISTNAME =	Net-Packet-Target-1.01
CATEGORIES =	net

MAINTAINER =	Jonathan Armani <armani@openbsd.org>

# Artistic License 1.0
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

BUILD_DEPENDS =  ${RUN_DEPENDS}

RUN_DEPENDS =	devel/p5-Class-Gomor \
		net/p5-Net-Packet

.include <bsd.port.mk>
