#!/bin/sh

test=0
require_sudo=0

if [ $# -lt 1 ]
then
	exit 1
fi

action=$1

if [ $action = "-t" ]
then
	if [ $# -ne 2 ]
	then
		exit 1
	fi
	action="$2"
	test=1
fi

case $action in
	halt)
		action="halt"
		require_sudo=1
		;;
	reboot)
		action="reboot"
		require_sudo=1
		;;
	suspend)
		action="zzz"
		;;
	*)
		exit 1
	#hibernate)
		# not supported for now
	#	;;		
esac
if [ $test -eq 1 ]
then
	if [ $require_sudo -eq 1 ]
	then
		sudo -n -l $action
	else
		exit 0
	fi
else
	if [ $require_sudo -eq 1 ]
	then
		sudo -n $action
	else
		sudo $action
	fi
fi

exit $?
