# $OpenBSD: Makefile,v 1.6 2011/01/16 01:05:50 laurent Exp $

     SUBDIR =
     SUBDIR += e
     SUBDIR += ecore
     SUBDIR += e_dbus
     SUBDIR += edje
     SUBDIR += eet
     SUBDIR += efreet
     SUBDIR += eina
     SUBDIR += embryo
     SUBDIR += evas

.include <bsd.port.subdir.mk>
