# $OpenBSD: Makefile,v 1.6 2011/01/16 01:05:50 laurent Exp $

SUBDIR =
SUBDIR += eina
SUBDIR += eet
SUBDIR += evas
SUBDIR += ecore
SUBDIR += embryo
SUBDIR += edje
SUBDIR += efreet
SUBDIR += e_dbus
SUBDIR += e
SUBDIR += expedite

.include <bsd.port.subdir.mk>
