# $OpenBSD$

COMMENT = python interface to packet filter

MODPY_EGG_VERSION =	0.0.5
DISTNAME =		py-PF-${MODPY_EGG_VERSION}
PKGNAME =           	${DISTNAME:L}

CATEGORIES =		net

HOMEPAGE =	http://www.kernel-panic.it/software/py-pf/	

MAINTAINER =	Jonathan Armani <armani@openbsd.org>

# GPLv2
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

MASTER_SITES =	${MASTER_SITE_SOURCEFORGE:=py-pf/}
EXTRACT_SUFX =  .tgz

MODULES = 	lang/python

.include <bsd.port.mk>
