# $OpenBSD$

COMMENT =	easy access to SQLite databases using objects	

MODULES =	cpan
DISTNAME =	DBIx-SQLite-Simple-0.34
CATEGORIES =	databases

MAINTAINER =	Jonathan Armani <armani@openbsd.org>

# Artistic License 1.0
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

BUILD_DEPENDS =  ${RUN_DEPENDS}

RUN_DEPENDS =	databases/p5-DBD-SQLite

.include <bsd.port.mk>
